- name: Install and Configure Prometheus, Grafana, Alertmanager, and Node Exporter
  hosts: monitoring_servers
  become: yes
  remote_user: tuxadm # Here insert your SSH user
  vars:
    ansible_ssh_pass: Pass_12345 # Here insert your SSH user's password
    ansible_become_password: Pass_12345 # Here insert your SSH sodoer user's password 
    prometheus_version: "2.31.1"
    alertmanager_version: "0.23.0"
    grafana_version: "8.3.3"
    node_exporter_version: "1.3.1"

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: 
          - curl
          - wget
          - software-properties-common
          - apt-transport-https
          - gnupg
        state: present

    - name: Add Prometheus user
      user:
        name: prometheus
        shell: /bin/false

    - name: Download and install Prometheus
      shell: |
        wget https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
        tar -xvf prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
        mv prometheus-{{ prometheus_version }}.linux-amd64 /etc/prometheus
        ln -s /etc/prometheus/prometheus /usr/local/bin/prometheus
        ln -s /etc/prometheus/promtool /usr/local/bin/promtool
      args:
        creates: /etc/prometheus

    - name: Create Prometheus directories
      file:
        path: /etc/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Create Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']

    - name: Create systemd service for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Download and install Alertmanager
      shell: |
        wget https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
        tar -xvf alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
        mv alertmanager-{{ alertmanager_version }}.linux-amd64 /etc/alertmanager
        ln -s /etc/alertmanager/alertmanager /usr/local/bin/alertmanager
      args:
        creates: /etc/alertmanager

    - name: Create Alertmanager directories
      file:
        path: /etc/alertmanager
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Create Alertmanager configuration file
      copy:
        dest: /etc/alertmanager/alertmanager.yml
        content: |
          route:
            receiver: 'default-receiver'

          receivers:
            - name: 'default-receiver'

    - name: Create systemd service for Alertmanager
      copy:
        dest: /etc/systemd/system/alertmanager.service
        content: |
          [Unit]
          Description=Alertmanager
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          ExecStart=/usr/local/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/var/lib/alertmanager/
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Alertmanager service
      systemd:
        name: alertmanager
        state: started
        enabled: yes

    - name: Download and install Grafana
      shell: |
        wget https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz
        tar -zxvf grafana-{{ grafana_version }}.linux-amd64.tar.gz
        mv grafana-{{ grafana_version }} /usr/local/grafana
        ln -s /usr/local/grafana/bin/grafana-server /usr/local/bin/grafana-server
        ln -s /usr/local/grafana/bin/grafana-cli /usr/local/bin/grafana-cli
      args:
        creates: /usr/local/grafana

    - name: Create systemd service for Grafana
      copy:
        dest: /etc/systemd/system/grafana.service
        content: |
          [Unit]
          Description=Grafana
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/usr/local/bin/grafana-server --homepath=/usr/local/grafana
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Grafana service
      systemd:
        name: grafana
        state: started
        enabled: yes

    - name: Download and install Node Exporter
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        tar -xvf node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        mv node_exporter-{{ node_exporter_version }}.linux-amd64 /etc/node_exporter
        ln -s /etc/node_exporter/node_exporter /usr/local/bin/node_exporter
      args:
        creates: /etc/node_exporter

    - name: Create systemd service for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
